# 几乎所有的demo
openai:
  api_key: CHAT_GPT_API_KEY

# 仅azure相关demo，地域可以选择eastus
azure:
  region: AZURE_SPEECH_REGION
  subscription: AZURE_SPEECH_KEY

# 仅did的demo
did:
  api_key: DID_API_KEY

# 仅huggingface inference api的demo
huggingface:
  api_key: HF_API_KEY
